apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-eureka-gateway-public
   
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-eureka-gateway-public
  template:
    metadata:
      labels:
        app: frontend-eureka-gateway-public
    spec:
      containers:
        - name: frontend
          image: fatnassihnifinassim353/espreat:1.0.0
          ports:
            - containerPort: 80
              name: frontend
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-eureka-gateway-public-service
spec:
  selector:
    app: frontend-eureka-gateway-public
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: front
  type: LoadBalancer
