apiVersion: v1
kind: Service
metadata:
  name: frontend-eureka-gateway-lb
spec:
  selector:
    app: frontend-eureka-gateway
  ports:
    - protocol: TCP
      port: 8099
      targetPort: 8099
      name: eureka
    - protocol: TCP
      port: 9090
      targetPort: 9090
      name: gateway
    - protocol: TCP
      port: 80
      targetPort: 80
      name: front
  type: LoadBalancer
