apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
  containers:
  - name: test-container
    image: curlimages/curl:latest  # Using curl image for simplicity
    command: ["sleep", "3600"]  # Keep the pod running
